config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  resources :items do
    resources :bids
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'session/new'
  root 'session#new'

# Omniauth routes
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

# bcrytp routes
  get '/signup' => 'admins#new'
  post '/admins' => 'admins#create'

  get  '/signin'   => 'admin_session#new'
  post '/signin'   => 'admin_session#create'
  get  '/signout'  => 'admin_session#destroy'

  #Mailer routes
  get '/prereport' => 'admins#send_pre_email'
  get '/final_report' => 'admins#send_post_email'

  mount Shrine::DownloadEndpoint => "/attachments"

  post 'favorites/:itemId'           => 'favorites#create'
  delete 'favorites/destroy/:itemId' => 'favorites#destroy'

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout false

  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to items_path
    else
      redirect_to root_path
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    redirect_to root_path
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <body class="custom-body">
    <div class="container">
    <div class="jumbotron landing-jumbotron">
      <h1 class="landing-heading">Welcome to The Bones Gala!</h1>
    </div>
    <div class="wrapper">
      <form class="form-signin">
        <h2 class="form-signin-heading">Please login</h2>
        <%= link_to auth_path(provider: 'github'), class: "btn btn-block btn-social btn-github" do %>
          <span class="fa fa-github"></span>Sign in with Github
        <% end %>
        <%= link_to auth_path(provider: 'twitter'), class: "btn btn-block btn-social btn-twitter" do %>
        <span class="fa fa-twitter"></span>Sign in with Twitter
        <% end %>
        <%= link_to auth_path(provider: 'facebook'), class: "btn btn-block btn-social btn-facebook" do %>
          <span class="fa fa-facebook"></span>Sign in with Facebook
        <% end %>
        <%= link_to auth_path(provider: 'google'), class: "btn btn-block btn-social btn-google" do %>
        <span class="fa fa-google"></span>Sign in with Google
        <% end %>
        <%= link_to signin_path, class: "landing-link" do %>
        <p class="landing-footer">Powered by Bidtastic! Copyright &copy; 2017 </p>
        <% end %>
      </form>
    </div>
  </div>
  </body>
  <footer>
  </footer>
</html>