config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  resources :items do
    resources :bids
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'session/new'
  root 'session#new'

# Omniauth routes
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

# bcrytp routes
  get '/signup' => 'admins#new'
  post '/admins' => 'admins#create'

  get  '/signin'   => 'admin_session#new'
  post '/signin'   => 'admin_session#create'
  get  '/signout'  => 'admin_session#destroy'

  #Mailer routes
  get '/prereport' => 'admins#send_pre_email'
  get '/final_report' => 'admins#send_post_email'

  mount Shrine::DownloadEndpoint => "/attachments"

  post 'favorites/:itemId'           => 'favorites#create'
  delete 'favorites/destroy/:itemId' => 'favorites#destroy'

end

app/models/item.rb
class Item < ApplicationRecord
  include ImageUploader[:image]

  has_many :favorites, dependent: :destroy
  has_many :bids

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :minimum_bid, presence: true
  validates :bid_increment, presence: true
  validates :image_data, presence: true

  def self.categories
    %W(Leisure Attire Jewelry Art Memorabilia/Antiques Other)
  end

  def largest_bid_amount
    # equivalent, shortcuts -- "symbol to proc"
    big_bid = bids.max_by(&:bid_amount)
    big_bid ? big_bid.bid_amount : "No Bids"
  end

  def bid_winner
    winner = bids.max_by(&:bid_amount)

    winner ? winner.created_by.name : "No Winner"
  end

  def next_minimum_bid
    bids_in_order = self.bids.order(:bid_amount)

    if bids_in_order.none?
      self.minimum_bid
    else
      highest_bid_so_far = bids_in_order.last

      highest_bid_so_far.bid_amount + self.bid_increment
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate!

  # GET /items
  def index
    search_category = params[:category]

    if search_category
      @items = Item.where(category: search_category)
    else
      @items = Item.all
    end
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    @item.created_by = current_user

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def item_params
    params.require(:item).permit(:name, :description, :category, :minimum_bid, :bid_increment, :image)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @item.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h4>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="fmtxt">

  <%# name %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>


  <%# description %>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>


  <%# category %>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :category, Item.categories.map { |category| [category, category] } %>
    </div>
  </div>


  <%# minimum_bid %>
  <div class="form-group">
    <%= f.label :minimum_bid, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :minimum_bid, class: "form-control" %>
    </div>
  </div>


  <%# bid_increment %>
  <div class="form-group">
    <%= f.label :bid_increment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :bid_increment, class: "form-control" %>
    </div>
  </div>


  <%# image_data %>
  <div class="form-group">
    <%= f.label :image_data, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.hidden_field :image, value: @item.cached_image_data %>
      <%= f.file_field :image %>

    </div>
  </div>

</div>


  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>
<% end -%>

app/views/items/edit.html.erb
<div class= "edhead">

<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Auction List
  <% end %>
  <%= link_to @item, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Item information
  <% end %>
  <h1>Edit: <%= @item.name %></h1>
 </div>
</div>
<%= render 'form' %>

app/views/items/index.html.erb
<div class="page-header">
  <% if admin_logged_in? %>
    <%= link_to new_item_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-plus-sign"></span>
        Add Auction Item
    <% end %>
    <%= link_to final_report_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-inbox"></span>
        Final Report
    <% end %>
    <%= link_to prereport_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-inbox"></span>
        PreAuction Report
    <% end %>
  <% end %>
  <h1 class="custom-header">Welcome to The Annual Bones' Gala Auction</h1>
</div>
<div class="row">
  <%- @items.each do |item| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="textline">
        <h3><%= item.name %></h3>
        <% if user_logged_in? && favorited(item.id) == true %>
          <p class="faved-heart" data-itemid="<%= item.id %>"> &hearts;</p>
        <% elsif user_logged_in? && favorited(item.id) == false %>
          <p class="fav-heart" data-itemid="<%= item.id %>"> &hearts;</p>
        <% end %>
      </div>

      <%= image_tag(item.image_url(:small)) %>
      <div class="caption">
        <% if item.bids.empty? %>
        <h3>Current Bid:</h3>
          <h4>No bids! Be the first to bid!</h4>
        <% else %>
          <h3>Current Bid:</h3>
          <h4><%= number_to_currency(item.largest_bid_amount, precision: 0) %></h4>
        <% end %>
        <h3> Description: </h3>
        <h4><%= truncate(item.description, length: 50, seperator: ' ') %></h4>
        <%= link_to item do %>
          <button class="placebid btn btn-default" role="button"><span class="glyphicon glyphicon-flag"  aria-hidden="true"></span>Place Bid</button>
        <% end %>
        <% if admin_logged_in? %>
          <%= link_to edit_item_path(item) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
          <%= link_to item, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New item</h1>
</div>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Auction List
  <% end %>
  <% if user_logged_in? && favorited(@item.id) == true %>
    <p class="faved-heart" data-itemid="<%= @item.id %>"> &hearts;</p>
  <% elsif user_logged_in? && favorited(@item.id) == false %>
    <p class="fav-heart" data-itemid="<%= @item.id %>"> &hearts;</p>
  <% end %>
  <% if admin_logged_in? %>
    <%= link_to edit_item_path(@item), class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit Item
    <% end %>
  <% end %>
  <h1><%= @item.name %></h1>
  <h4><%= @item.category %></h4>
</div>
<div class="row media-tex">
  <div class="col-xs-12 col-md-4 item-show-image">
    <%= image_tag(@item.image_url(:medium), class: "img-responsive") %>
  </div>
  <div class="col-xs-12 col-md-8">
    <h3> <%= @item.description %></h3>
    <h3>Minimum Bid: <%= number_to_currency(@item.minimum_bid, precision: 0) %></h3>
    <h3>Bidding Increment: <%= number_to_currency(@item.bid_increment, precision: 0) %></h3>
  </div>
</div>
<div class="body-show">
  <h3> Current Bids:</h3>
  <ul class="list-group">
    <% if user_logged_in? %>
      <li class="list-group-item bidamount-list-group-item"><%= render "bids/form" %></span></li>
    <% end %>
    <%= render @item.bids.order(bid_amount: :desc) %>
  </ul>
</div>