config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  resources :items do
    resources :bids
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'session/new'
  root 'session#new'

# Omniauth routes
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

# bcrytp routes
  get '/signup' => 'admins#new'
  post '/admins' => 'admins#create'

  get  '/signin'   => 'admin_session#new'
  post '/signin'   => 'admin_session#create'
  get  '/signout'  => 'admin_session#destroy'

  #Mailer routes
  get '/prereport' => 'admins#send_pre_email'
  get '/final_report' => 'admins#send_post_email'

  mount Shrine::DownloadEndpoint => "/attachments"

  post 'favorites/:itemId'           => 'favorites#create'
  delete 'favorites/destroy/:itemId' => 'favorites#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "/", class: "navbar-brand" do %>
          Bidtastic
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", items_path %></li>
          <li class="category-link active"><%= link_to "Attire", items_path %></li>
          <li class="category-link active"><%= link_to "Leisure", items_path %></li>
          <li class="category-link active"><%= link_to "Jewelry", items_path %></li>
          <li class="category-link active"><%= link_to "Art", items_path %></li>
          <li class="category-link active"><%= link_to "Memorabilia", items_path %></li>
          <li class="category-link active"><%= link_to "Other", items_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <% if user_logged_in? %>
            <li><%= link_to 'Logout', logout_path, data: { confirm: 'Are you sure?' } %></li>
          <% end %>
          <% if admin_logged_in? %>
            <li><%= link_to 'Signout', signout_path, data: { confirm: 'Are you sure?' } %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>